coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: 80%
        informational: true

flag_management:
  default_rules:
    carryforward: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "**/migrations/**"
  - "**/src/testing/**"
  - "**/main.ts"
  - "**/*.module.ts"
  - "**/*.generated.ts"
  - "**/*.g.ts"
  - "**/*.d.ts"
  - "**/index.ts"
  - "**/instrumentation.ts"
  - "**/typeorm-options.ts"
