export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-empty': [2, 'never'],
    'scope-enum': [
      2,
      'always',
      [
        'gateway',
        'auth',
        'catalog',
        'search',
        'order',
        'inventory',
        'payment',
        'delivery',
        'notification',
        'media',
        'analytics',
        'review',
        'config',
        'shared-config',
        'shared-health',
        'shared-logging',
        'shared-jwt',
        'shared-tenancy',
        'shared-locking',
        'shared-cache',
        'shared-messaging',
        'shared-observability',
        'shared-settings',
        'shared-contracts',
        'shared-errors',
        'shared-persistence',
        'infra',
        'ci',
      ],
    ],
  },
};
