apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: search
    app.kubernetes.io/part-of: food-delivery
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: search
  ports:
    - name: http
      port: 3004
      targetPort: http
