upstream api_gateway {
    server host.docker.internal:3000;
}

map $http_x_correlation_id $correlation_id {
    default $http_x_correlation_id;
}

server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://api_gateway;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Correlation-Id $correlation_id;
    }
}
