apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: food-delivery
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
