apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: food-delivery
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: Y2hhbmdlbWUtZGV2LW9ubHk=
  POSTGRES_DB: Y2F0YWxvZw==
