apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter-config
  namespace: observability
  labels:
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/part-of: food-delivery
data:
  config.yaml: |
    rules:
      - seriesQuery: 'http_server_request_duration_seconds_count{namespace!="",pod!=""}'
        resources:
          overrides:
            namespace: { resource: "namespace" }
            pod: { resource: "pod" }
        name:
          matches: "^http_server_request_duration_seconds_count$"
          as: "http_requests_per_second"
        metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'
