apiVersion: v1
kind: Service
metadata:
  name: prometheus-adapter
  namespace: observability
  labels:
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/part-of: food-delivery
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prometheus-adapter
  ports:
    - name: https
      port: 443
      targetPort: https
