apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: notification
    app.kubernetes.io/part-of: food-delivery
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: notification
  ports:
    - name: http
      port: 3012
      targetPort: http
