syntax = "proto3";

package inventory;

service InventoryService {
  rpc Reserve (ReserveRequest) returns (ReserveResponse);
  rpc Release (ReleaseRequest) returns (ReleaseResponse);
}

message ReserveItem {
  string item_id = 1;
  int32 qty = 2;
}

message ReserveRequest {
  string tenant_id = 1;
  string order_id = 2;
  repeated ReserveItem items = 3;
}

message ReserveResponse {
  bool ok = 1;
  repeated string reservation_ids = 2;
}

message ReleaseRequest {
  string tenant_id = 1;
  string order_id = 2;
}

message ReleaseResponse {
  bool ok = 1;
}
