namespace: food-delivery
resources:
  - namespace.yaml
  - internal-identity
  - gateway
  - catalog
  - auth
  - order
  - search
  - delivery
  - media
  - payment
  - config
  - review
  - analytics
  - inventory
  - notification
  - ingress.yaml
  - network-policies

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/startupProbe
        value:
          httpGet:
            path: /api/v1/health
            port: http
          periodSeconds: 10
          failureThreshold: 30
      - op: add
        path: /spec/template/spec/containers/0/lifecycle
        value:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 5"]
      - op: add
        path: /spec/template/spec/terminationGracePeriodSeconds
        value: 30
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          secretRef:
            name: internal-identity-secret
