namespace: food-delivery
resources:
  - ../../base
  - ../../infra-dev
patches:
  - target:
      kind: ConfigMap
      labelSelector: food-delivery.io/config-kind=app-env
    patch: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: placeholder
      data:
        TELEMETRY_ENABLED: "false"
