apiVersion: v1
kind: Service
metadata:
  name: config
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: config
    app.kubernetes.io/part-of: food-delivery
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: config
  ports:
    - name: http
      port: 3008
      targetPort: http
