apiVersion: v1
kind: Secret
metadata:
  name: analytics-secret
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: analytics
    app.kubernetes.io/part-of: food-delivery
type: Opaque
data:
  CLICKHOUSE_USER: ZGVmYXVsdA==
  CLICKHOUSE_PASSWORD: 
