apiVersion: v1
kind: Service
metadata:
  name: analytics
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: analytics
    app.kubernetes.io/part-of: food-delivery
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: analytics
  ports:
    - name: http
      port: 3010
      targetPort: http
