apiVersion: v1
kind: Secret
metadata:
  name: internal-identity-secret
  namespace: food-delivery
  labels:
    app.kubernetes.io/part-of: food-delivery
type: Opaque
data:
  INTERNAL_IDENTITY_SIGNING_KEY: Y2hhbmdlbWUtZGV2LW9ubHktaW50ZXJuYWwtaWRlbnRpdHktc2lnbmluZy1rZXk=
