apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/part-of: food-delivery
    food-delivery.io/config-kind: app-env
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability:4318"
  TELEMETRY_ENABLED: "true"
  PORT: "3011"
  DB_HOST: "postgres.food-delivery"
  DB_PORT: "5432"
  DB_NAME: "inventory"
  REDIS_URL: "redis://redis.food-delivery:6379"
  INVENTORY_GRPC_URL: "0.0.0.0:50052"
  KAFKA_BROKERS: "kafka.food-delivery:9092"
  KAFKA_CLIENT_ID: "inventory"
