apiVersion: v1
kind: Secret
metadata:
  name: inventory-secret
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/part-of: food-delivery
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: Y2hhbmdlbWUtZGV2LW9ubHk=
