apiVersion: v1
kind: Service
metadata:
  name: inventory
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/part-of: food-delivery
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: inventory
  ports:
    - name: http
      port: 3011
      targetPort: http
    - name: grpc
      port: 50052
      targetPort: grpc
