apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: default-deny-all
    app.kubernetes.io/part-of: food-delivery
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
