apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-otlp-egress-to-observability
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: allow-otlp-egress-to-observability
    app.kubernetes.io/part-of: food-delivery
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
      ports:
        - protocol: TCP
          port: 4318
        - protocol: TCP
          port: 4317
