apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-postgres
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: ingress-postgres
    app.kubernetes.io/part-of: food-delivery
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: food-delivery
      ports:
        - protocol: TCP
          port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-redis
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: ingress-redis
    app.kubernetes.io/part-of: food-delivery
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redis
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: food-delivery
      ports:
        - protocol: TCP
          port: 6379
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-kafka
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: ingress-kafka
    app.kubernetes.io/part-of: food-delivery
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kafka
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: food-delivery
      ports:
        - protocol: TCP
          port: 9092
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-temporal
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: ingress-temporal
    app.kubernetes.io/part-of: food-delivery
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: temporal
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: payment
      ports:
        - protocol: TCP
          port: 7233
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-keycloak
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: ingress-keycloak
    app.kubernetes.io/part-of: food-delivery
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gateway
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: auth
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: delivery
      ports:
        - protocol: TCP
          port: 8080
