apiVersion: v1
kind: Secret
metadata:
  name: media-secret
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: media
    app.kubernetes.io/part-of: food-delivery
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: Y2hhbmdlbWUtZGV2LW9ubHk=
  MINIO_ACCESS_KEY: bWluaW9hZG1pbg==
  MINIO_SECRET_KEY: Y2hhbmdlbWUtZGV2LW9ubHk=
