apiVersion: v1
kind: Service
metadata:
  name: media
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: media
    app.kubernetes.io/part-of: food-delivery
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: media
  ports:
    - name: http
      port: 3006
      targetPort: http
