apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/part-of: food-delivery
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: Y2hhbmdlbWUtZGV2LW9ubHk=
  KEYCLOAK_ADMIN: YWRtaW4=
  KEYCLOAK_ADMIN_PASSWORD: Y2hhbmdlbWUtZGV2LW9ubHk=
