apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/part-of: food-delivery
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth
  ports:
    - name: http
      port: 3002
      targetPort: http
